import images from "../../components/exports/images";

export const TeamData = [
  {
    name: "Matthew Miller",
    role: "CEO & Dapp Creator",
    small: " Set a meet @calendy",
    imageUrl: images.team17,
    twLink: "https://twitter.com/WolfPackHerd",
    tgramLink: "https://twitter.com/WolfPackHerd",
    linkedLink: "https://twitter.com/WolfPackHerd",
    emailLink: "mailto:https://twitter.com/WolfPackHerd",
  },
  {
    name: "Mike Dre",
    role: "Advisor",
    imageUrl: images.team16,
    twLink: "https://twitter.com/WolfPackHerd",
    tgramLink: "https://twitter.com/WolfPackHerd",
    linkedLink: "https://twitter.com/WolfPackHerd",
    emailLink: "mailto:https://twitter.com/WolfPackHerd",
  },
  {
    name: "Gregg Schultz",
    role: "Advisor",
    imageUrl: images.team15,
    twLink: "https://twitter.com/WolfPackHerd",
    tgramLink: "https://twitter.com/WolfPackHerd",
    linkedLink: "https://twitter.com/WolfPackHerd",
    emailLink: "mailto:https://twitter.com/WolfPackHerd",
  },
  {
    name: "Hon Afo",
    role: "Community Manager",
    imageUrl: images.team14,
    twLink: "https://twitter.com/WolfPackHerd",
    tgramLink: "https://twitter.com/WolfPackHerd",
    linkedLink: "https://twitter.com/WolfPackHerd",
    emailLink: "mailto:https://twitter.com/WolfPackHerd",
  },
  {
    name: "Olumayowa",
    role: "Blockchain Lawyer",
    imageUrl: images.team13,
    twLink: "https://twitter.com/WolfPackHerd",
    tgramLink: "https://twitter.com/WolfPackHerd",
    linkedLink: "https://twitter.com/WolfPackHerd",
    emailLink: "mailto:https://twitter.com/WolfPackHerd",
  },
  {
    name: "Joshade",
    role: "Smart Contract Developer",
    imageUrl: images.team12,
    twLink: "https://twitter.com/WolfPackHerd",
    tgramLink: "https://twitter.com/WolfPackHerd",
    linkedLink: "https://twitter.com/WolfPackHerd",
    emailLink: "mailto:https://twitter.com/WolfPackHerd",
  },
  {
    name: "Sodeeq",
    role: "Frontend Developer",
    imageUrl: images.team11,
    twLink: "https://twitter.com/WolfPackHerd",
    tgramLink: "https://twitter.com/WolfPackHerd",
    linkedLink: "https://twitter.com/WolfPackHerd",
    emailLink: "mailto:https://twitter.com/WolfPackHerd",
  },
  {
    name: "Semilayer",
    role: "Backend Developer",
    imageUrl: images.team10,
    twLink: "https://twitter.com/WolfPackHerd",
    tgramLink: "https://twitter.com/WolfPackHerd",
    linkedLink: "https://twitter.com/WolfPackHerd",
    emailLink: "mailto:https://twitter.com/WolfPackHerd",
  },
  {
    name: "Lef",
    role: "Backend Developer",
    imageUrl: images.team9,
    twLink: "https://twitter.com/WolfPackHerd",
    tgramLink: "https://twitter.com/WolfPackHerd",
    linkedLink: "https://twitter.com/WolfPackHerd",
    emailLink: "mailto:https://twitter.com/WolfPackHerd",
  },
  {
    name: "Gloria Ojo",
    role: "Lead UX Designer",
    imageUrl: images.team8,
    twLink: "https://twitter.com/WolfPackHerd",
    tgramLink: "https://twitter.com/WolfPackHerd",
    linkedLink: "https://twitter.com/WolfPackHerd",
    emailLink: "mailto:https://twitter.com/WolfPackHerd",
  },
];
